### PR TITLE
Added PCA code in python 

### PR DESCRIPTION
**Pull request by Duxy1996**
Added PCA code in python this afternoon i will upload the LDA code. It has a vectorial representation. The original code was in matlab,

### CODE REVIEW

**Comment by SilentFlame** [comment]
Would be better if you add a test file in place of a single test.

That will help others to test on larger no. of inputs if needed.

Rest all is fine. :)

**Comment by Duxy1996** [comment]
Thank for all, I'm going to work todo the test, and I'm going to try to improve the cost of the operations. Im having a little trouble with the PCA algorithm, but I think tomorrow I will have it.

**Comment by Duxy1996** [comment]
I have done all, but I want to make more test, bcs I used a very little data.

**Comment by SilentFlame** [comment]
This is fine as of now.

Wil merge this, but will expect you to add more tests here.
Thanks @Duxy1996  :)

**Pull request merged**
